version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "@types/jest"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/query-string"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/react-router-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@typescript-eslint/parser"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@vitejs/plugin-react"
        update-types: ["version-update:semver-major"]
      - dependency-name: eslint
        update-types: ["version-update:semver-major"]
      - dependency-name: eslint-config-prettier
        update-types: ["version-update:semver-major"]
      - dependency-name: eslint-plugin-prettier
        update-types: ["version-update:semver-major"]
      - dependency-name: eslint-plugin-react
        update-types: ["version-update:semver-major"]
      - dependency-name: jest
        update-types: ["version-update:semver-major"]
      - dependency-name: prettier
        update-types: ["version-update:semver-major"]
      - dependency-name: react-router-dom
        update-types: ["version-update:semver-major"]
      - dependency-name: sass
        update-types: ["version-update:semver-major"]
      - dependency-name: typescript
        update-types: ["version-update:semver-major"]
      - dependency-name: vite
        update-types: ["version-update:semver-major"]
