version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: axios
        update-types: ["version-update:semver-major"]
      - dependency-name: vue
        update-types: ["version-update:semver-major"]
      - dependency-name: vue-i18n
        update-types: ["version-update:semver-major"]
      - dependency-name: vuex
        update-types: ["version-update:semver-major"]
      - dependency-name: "@vitejs/plugin-vue"
        update-types: ["version-update:semver-major"]
      - dependency-name: eslint
        update-types: ["version-update:semver-major"]
      - dependency-name: eslint-config-prettier
        update-types: ["version-update:semver-major"]
      - dependency-name: eslint-plugin-vue
        update-types: ["version-update:semver-major"]
      - dependency-name: gh-pages
        update-types: ["version-update:semver-major"]
      - dependency-name: prettier
        update-types: ["version-update:semver-major"]
      - dependency-name: sass
        update-types: ["version-update:semver-major"]
      - dependency-name: vite
        update-types: ["version-update:semver-major"]
